# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG BASE_IMAGE

FROM $BASE_IMAGE AS BASE

ARG AZL_VERSION=3.0

ARG RPMS_TO_INSTALL
ARG RPMS_PATH="/dockerStage/RPMS"
ARG LOCAL_REPO_FILE="/dockerStage/azurelinuxlocal.repo"
ARG LOCAL_REPO_PATH="/localrepo"

# Create local repo with the given RPMS.
# This will allow the user to install packages from the local repo
# instead of fetching from PMC
RUN --mount=type=bind,source=./Stage/,target=/dockerStage/ \
    mkdir -p ${LOCAL_REPO_PATH}/RPMS; \
    tdnf install -y --releasever=$AZL_VERSION createrepo; \
    cp /dockerStage/RPMS/*.rpm ${LOCAL_REPO_PATH}/RPMS/; \
    cp ${LOCAL_REPO_FILE} /etc/yum.repos.d/local.repo; \
    createrepo --compatibility --database ${LOCAL_REPO_PATH}/RPMS --workers 10; \
    chmod -R a+rX ${LOCAL_REPO_PATH}; \
    tdnf makecache; \
    tdnf autoremove -y createrepo;

# Install packages into a staging location.
RUN mkdir /staging \
    && tdnf install -y --releasever=$AZL_VERSION --installroot /staging \
    ${RPMS_TO_INSTALL} \
    && tdnf clean all \
    && mkdir -p /staging/bin \
    && ln -sf /sbin/busybox /staging/bin/sh

# Smoke Tests
RUN chroot /staging /sbin/busybox --install -s /bin && \
    chroot /staging /bin/sh -xec 'true'

# Ensure correct timezone (UTC)
RUN [ "$(chroot /staging date +%Z)" = 'UTC' ]

# Test and make sure DNS works too
RUN mkdir -p /staging/etc && \
    cp -L /etc/resolv.conf /staging/etc/ && \
    chroot /staging /bin/sh -xec 'nslookup microsoft.com' && \
    rm /staging/etc/resolv.conf

FROM scratch

# Copy dependencies into the scratch image.
COPY --from=BASE /staging/ .
COPY --from=BASE EULA-Container.txt /
CMD [ "sh" ]
